### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gsgoldma** [AUTOMATIC1111/stable-diffusion-webui-pixelization#1]
Error loading script: postprocessing_pixelization.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-pixelization\scripts\postprocessing_pixelization.py", line 15, in <module>
    from models.networks import define_G
ModuleNotFoundError: No module named 'models.networks'

**Comment by Nacurutu** [comment]
Same error on my end:

```
Error loading script: postprocessing_pixelization.py
Traceback (most recent call last):
  File "C:\AI\WebUI\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\WebUI\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\AI\WebUI\extensions\stable-diffusion-webui-pixelization\scripts\postprocessing_pixelization.py", line 15, in <module>
    from models.networks import define_G
ModuleNotFoundError: No module named 'models.networks'
```

**Comment by Nacurutu** [comment]
Working properly after last update
