### ISSUE TITLE
2023.3.3 ModuleNotFoundError: No module named 'pixelization'

### ISSUE THREAD

**Issue by kenshin20080-lab** [AUTOMATIC1111/stable-diffusion-webui-pixelization#12]
2023.3.3 12:00

Error loading script: postprocessing_pixelization.py
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/kaggle/working/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/kaggle/working/stable-diffusion-webui/extensions/pixelization/scripts/postprocessing_pixelization.py", line 13, in <module>
    from pixelization.models.networks import define_G
ModuleNotFoundError: No module named 'pixelization'

**Comment by PengZiqiao** [comment]
clone https://github.com/WuZongWei6/Pixelization.git to stable-diffusion-webui/extensions/stable-diffusion-webui-pixelization/pixelization will solve the problem

**Comment by Dcc-pixel** [comment]
> [将https://github.com/WuZongWei6/Pixelization.git](https://github.com/WuZongWei6/Pixelization.git)克隆到 stable-diffusion-webui/extensions/stable-diffusion-webui-pixelization/pixelization 将解决问题

并没有解决，老哥还有什么办法吗
