### ISSUE TITLE
2023.03.10 AttributeError

### ISSUE THREAD

**Issue by yyygambare** [AUTOMATIC1111/stable-diffusion-webui-pixelization#13]
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=307x411 at 0x7F04C6A3DE80>, None, '', '', True, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, True, False, 3) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/postprocessing.py", line 56, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-pixelization/scripts/postprocessing_pixelization.py", line 212, in process
    pp.image = to_image(out_t, pixel_size=pixel_size, upscale_after=upscale_after)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-pixelization/scripts/postprocessing_pixelization.py", line 161, in to_image
    img = img.resize((img.size[0]//4, img.size[1]//4), resample=Image.Resampling.NEAREST)
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'

I'm using it at colab, but it doesn't work.

**Comment by Dcc-pixel** [comment]
Excuse me, is there any solution?
