### ISSUE TITLE
Issue using latest version

### ISSUE THREAD

**Issue by BoBoBiBop** [AUTOMATIC1111/stable-diffusion-webui-pixelization#7]
I'm attempting to use the pixelization addon for webUI; but everytime I load up webui-user.bat this error pops up, and the addon is no where to be seen in the UI.

`Error loading script: postprocessing_pixelization.py
Traceback (most recent call last):
  File "C:\Users\Barack\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Barack\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\Barack\stable-diffusion-webui\extensions\stable-diffusion-webui-pixelization\scripts\postprocessing_pixelization.py", line 3, in <module>
    from modules import scripts_postprocessing, devices, scripts
ImportError: cannot import name 'scripts_postprocessing' from 'modules' (unknown location)`

**Comment by xvwx** [comment]
Same there

**Comment by Dcc-pixel** [comment]
Excuse me, is there any solution?
